apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  ports:
  - name: ftp-data
    port: 20
    targetPort: 20
    protocol: TCP
  - name: ftp-command
    port: 21
    targetPort: 21
    protocol: TCP
  - name: pasv
    port: 31000
    targetPort: 31000
    protocol: TCP
  selector:
    app: ftps
  loadBalancerIP: 192.168.99.127

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pv-claim
  namespace: default
  labels:
    app: ftps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      name: ftps
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: services-ftps
        imagePullPolicy: Never
        ports:
        - name: ftp-data
          containerPort: 20
        - name: ftp-command
          containerPort: 21
        - name: pasv
          containerPort: 31000
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /ftps_user
        - name: vsftpd-config
          mountPath: /etc/vsftpd/vsftpd.conf
          subPath: vsftpd.conf
          readOnly: true
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
      - name: vsftpd-config
        configMap:
          name: vsftpd-config
