apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  labels:
    app: grafana
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: grafana
  loadBalancerIP: 192.168.99.126

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: services-grafana
        imagePullPolicy: Never
        ports:
        - name: grafana
          containerPort: 3000
        volumeMounts:
        - name: grafana-config
          mountPath: /usr/share/grafana/conf/grafana.ini
          subPath: grafana.ini
          readOnly: true
        envFrom:
        - secretRef:
            name: grafana-secrets
      volumes:
      - name: grafana-config
        configMap:
          name: grafana-config