apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secrets
  labels:
    app: telegraf
type: Opaque
stringData:
  INFLUXDB_DB: telegraf
  INFLUXDB_URL: http://influxdb:8086
  INFLUXDB_USER: root
  INFLUXDB_USER_PASSWORD: root
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  strategy:
    type: Recreate
  minReadySeconds: 5
  template:
    metadata:
      name: telegraf
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: services-telegraf
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /etc/telegraf/telegraf.conf
          name: telegraf-config
          subPath: telegraf.conf
          readOnly: true
        - name: docker-socket
          mountPath: /var/run/docker.sock
        envFrom:
        - secretRef:
            name: telegraf-secrets
      volumes:
      - name: telegraf-config
        configMap:
          name: telegraf-config
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
